service: serverless-flask

plugins:
  - serverless-wsgi
  - serverless-python-requirements 

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    layer: true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }

package:
  exclude:
    - package*
    - serverless*
    - node_modules/**
    - venv/**

